spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/revenue_dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Ptech6441
    driver-class-name: com.mysql.cj.jdbc.Driver


kafka:
  topic:
  host:
  port:
  group-id:
  auto-offset-reset:
