server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
  datasource:
    url: jdbc:mysql://localhost:3306/revenue?useUnicode=true&characterEncoding=utf8
    username: chkkang
    password: 1234
    driver-class-name:  com.mysql.cj.jdbc.Driver

kafka:
  topic:
    business-topic: business
